######################################
# <Basics>
#	1. File: Makefile
#	2. Date: 20120214_102709
#	3. Author: Iwabuchi Ken
######################################
CC=bcc32
CFLAGS=-N -v -w -ml

calc1_bcc.exe: calc1.c
	$(CC) $(FLAGS) -ecalc1_bcc.exe calc1.c
	
clean:
	erase *bcc*

calc2_bcc.exe: calc2.c
	$(CC) $(FLAGS) -ecalc2_bcc.exe calc2.c